channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.0
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1e
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.1
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.5.0
  - tornado=6.0.4
  - tqdm=4.43.0
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - boto3==1.12.31
    - botocore==1.15.31
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.1.1
    - dataclasses==0.7
    - docutils==0.15.2
    - filelock==3.0.12
    - gast==0.2.2
    - google-auth==1.12.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.9
    - ipdb==0.13.2
    - jmespath==0.9.5
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - nltk==3.5
    - oauthlib==3.1.0
    - opt-einsum==3.2.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - regex==2020.2.20
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - sentence-transformers==0.2.6.1
    - sentencepiece==0.1.85
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - tokenizers==0.5.2
    - transformers==2.8.0
    - urllib3==1.25.8
    - werkzeug==1.0.0
    - wrapt==1.12.1

